### ISSUE TITLE
Unable to get working Mobile client ...

### ISSUE THREAD

**Issue by scramatte** [uprel/gisapp#102]
Hi,

I'm unable to get working Mobile client.
¿Can you give me an hand ? I've got a blank page ...

![image](https://user-images.githubusercontent.com/188766/61865670-eda72f00-aed3-11e9-9c82-6786dec59a70.png)

**Comment by uprel** [comment]
This means an error, can you open developers console with F12, reload page and post error from console here. I'll check that.

**Comment by uprel** [comment]
It is possible that is this bug #99 , meeaning you have some layers checked off for identify in QGIS Project properties.

**Comment by scramatte** [comment]
still doesn't work, all my spatial layers are checked for identify.

**Comment by uprel** [comment]
Yes, must be some error. We will continue on email with this

**Comment by uprel** [comment]
Can you send me to my email login data for your gisapp project and I will debug myself

**Comment by scramatte** [comment]
I've just send you a mail wit credentials. By the way you can see what occurs with pan whole map ...

**Comment by uprel** [comment]
Problem was with loading plain tables in QGIS project. That was fixed in code for upcoming release 1.9.0
