### ISSUE TITLE
Support Spatial Bookmarks?

### ISSUE THREAD

**Issue by scramatte** [uprel/gisapp#105]
Hi,

How does it posible to have spacial markers into viewer?
Regards

**Comment by uprel** [comment]
Can you describe more what do you mean?
Is the problem with fonts (for example you see your points on desktop fine, but on server not). In this case fonts must be copied on correct location on server - https://docs.qgis.org/3.4/en/docs/user_manual/working_with_ogc/server/config.html#id7

**Comment by scramatte** [comment]
No,  I mean  Spatial Bookmarks. Sorry for my translation ...
![image](https://user-images.githubusercontent.com/188766/65369863-07a28b00-dc53-11e9-9b85-4e367715e275.png)

**Comment by uprel** [comment]
Bookmarks are currently not supported, so this can be good idea to implement. Of course every bookmark should be saved in project for the client to use.  I have to check how they are stored in project and how to load them in client. Some work to do.

**Comment by scramatte** [comment]
I believe that bookmarks are global to qgis and it's possible to export them as XML.

**Comment by uprel** [comment]
Project spatial bookmarks (must be saved into project) for QGIS 3.10 or newer are supported now in both clients with commits
0a2e1505d9108c723bcf8525a60ed07f61c2b45b
4c2aa8b2e4148f6d9ce7aadccea7179ea1f70c3f
