### ISSUE TITLE
Unable to get a working client

### ISSUE THREAD

**Issue by eythimisKyrikos** [uprel/gisapp#109]
Hi, 
I tried installing the client in ubuntu 19.10 following the instructions but when I go to localhost/gisapp/helloworld I get the php source file, not the client. 
Do you have any thoughts why this is happening?

![gisapp_hello](https://user-images.githubusercontent.com/35466482/72733331-4f550700-3ba0-11ea-992f-4bbfd7edb864.png)

**Comment by uprel** [comment]
Setup for Apache is not working or not finished. Did you copy and enable gisapp.conf?
https://github.com/uprel/gisapp/wiki/2.-Setup#2-apache-configuration

Also edit gisapp.conf and check your paths. If you don't have gisapp folder in /var/www/html/gisapp then you need to modify paths also in gisapp.conf (the one that will be used by Apache, so in /etc/apache2/conf-available)
