### ISSUE TITLE
WSGI, qwc_connect.py has been overwritten after git update

### ISSUE THREAD

**Issue by scramatte** [uprel/gisapp#125]
Hello,

for some reason, when I update git repository , qwc_connect.py script has been overwritten.
due to this reason  script was unable connect to database to search streets ...

regards

**Comment by uprel** [comment]
Always is possible and normal to have some locally changed files and this changes are preserved when doing git pull from server. What happened in your case I don't know.

Other config files I have excluded from repository, but here I left it. It's not the best way to have another settings file, I know. Best would be to move database connection details somewhere else.

**Comment by uprel** [comment]
I changed this logic now and moved qwc_connect.py outside of this repository. There are also many other changes in WSGI so read release notes for 1.9.9.  This update will again delete qwc_connect, but just this time, later not any more.
