### ISSUE TITLE
Windows installation problems

### ISSUE THREAD

**Issue by nigr0nyx** [uprel/gisapp#16]
Hi, i`m trying to install Extended QGIS Web Client on Windows.
I did every step in Setup manual and i have an error:

> Parse error: syntax error, unexpected T_STRING, expecting T_CONSTANT_ENCAPSED_STRING or > '(' in C:\OSGeo4W\apache\htdocs\gisapp\index.php on line 3.

PHP version is
> C:\OSGeo4W\bin>php.exe -v
> PHP 5.2.5 (cli) (built: Nov  8 2007 23:18:51)

Any Ideas?
Thanks.

**Comment by uprel** [comment]
Will have to take a look, I had a working version on Windows in earlier stage, not now. PHP is very old, some workarounds are needed. Is this mainly for testing purposes?

**Comment by nigr0nyx** [comment]
> Is this mainly for testing purposes?
If installation will be successful, I'm going to use client for my project.

**Comment by uprel** [comment]
Fix now with 1.0.6, look at new settings template for windows. For installing QGIS Server on Win 10 read this - [http://level2.si/index.php/2015/12/19/qgis-server-on-windows-10/](http://level2.si/index.php/2015/12/19/qgis-server-on-windows-10/)
