### ISSUE TITLE
Project doesn’t exists. Add correct project name and reload the page.

### ISSUE THREAD

**Issue by anakin1230** [uprel/gisapp#22]
I try to install it on Ubuntu 15.10.
So far, the “normal” Qgis-Webclient is running well, but calling your extended web client i get:
“Project doesn’t exists. Add correct project name and reload the page.”
I installed the database and tried to use the demo, included in the package.

Do you have hint?

BTW: //project location - what does it mean? apache? or normal qgis-web-client projects folder?

**Comment by uprel** [comment]
I think Apache configuration is not completed. Please check updated Wiki pages and then we can continue to discuss it through email.
