### ISSUE TITLE
Got PINK layer over my map... 

### ISSUE THREAD

**Issue by scramatte** [uprel/gisapp#28]
Hi,

I've setup gisapp following step by step wiki instructions.
Every looks ok,  including  hello world example is working.

My problem is that I'm unable to get working any other project.
I've added project to the database.  But when I open browser,  I got  "pink layer" over my map and don't see any maps objects.

Note that with standard "QGIS-Web-Client", same project works perfectly.

Any idea of what occurs here ?

**Comment by uprel** [comment]
Hi,
Exact same name of project added to database (inlcuding case) must exist in your folder. Check that and also check base layers. Try without or with same conf. as it is in Helloworld project.
If this server is online I can also check, send me details on uros@level2.si.
regards
Uroš

**Comment by uprel** [comment]
Check also QGISSERVER url in admin/settings.php. Pink image could come as aresult of broken base layer or could be qgis server error.

**Comment by uprel** [comment]
As of version 1.30 pink tiles are shown transparent, so no more annoying pink color. But of course there is other issue why image is not drawn in your case.
