### ISSUE TITLE
Unable to log in

### ISSUE THREAD

**Issue by bonegabor** [uprel/gisapp#30]
Hello,

This is my first time configuring the EQWC, and unfortunately am stuck. A get the error message, which says only 'Unable to log in', even with the guest (this is with helloword). I have no idea how to continue from here. 

The system is configured on a server running with CentOS 7, with multiple virtual host. 

Do you have any idea where am I got stuck?
Thank you,
Gábor

**Comment by uprel** [comment]
Check if you have correctly setup settings.php and also look in Apache error log.

**Comment by bonegabor** [comment]
Hello,

Thanks for your answer. Unfortunately I could not figure out what the problem is. Apache error log shows nothing, and settings.php is correct, (as a I think). 
The link where you can see my project is http://harta.atlaspasari.ro/gisapp/helloworld?public=on .
Can you have a look on it please? 

Thank you,
Gabor

**Comment by uprel** [comment]
I think problem is with accessing the database. Error should be visible from Apache log. Also postgresql log might be helpful. Postgres version must be 9.3. or higher. Send me these logs and settings.php and I will check. Email uros@level2.si

**Comment by uprel** [comment]
Problem was due to old version of PostgreSQL 9.2

**Comment by bonegabor** [comment]
Thank you for your help and for your application.  I've upgraded my postgrsql and now it works. :+1:

**Comment by teckefaro** [comment]
Hello
This is a first choice with a configuration of the EQWC and, now in a pass over front, in the problem of login of access.

- PostgreSQL e o 10.6-1 64 bit.
- PHP 5.5.26.
- Qgis-server is working correctly with manual configuration tests.
- About setting the settings.php file.
`<?php
define('DEFAULT_LANG', 'en');
define('DEBUG', false);
define('DB_CONN_STRING', 'pgsql:host=localhost;port=5432;dbname=gisapp');
define('DB_USER', 'postgres');
define('DB_PWD', 'postgres');
define('PROJECT_PATH', 'D:/SERVIDOR/wamp64/www/04TESTE/gisapp/_demo/');
define('QGISSERVERURL', 'http://localhost/cgi-bin/qgis_mapserv.fcgi.exe');
define('QGISSERVERCACHE', false);
define('GOOGLE_MAPS_KEY','your_key');
define('MAPBOX_KEY','your_access_token');
define('MAIN_UPLOAD_DIR', 'uploads/');
define('OGR2OGR', 'C:/OSGeo4W64/bin/ogr2ogr');
define('TEMP_PATH', 'C:/Temp');
define('GISAPPURL', '/gisapp/');`

this error appears:
![image](https://user-images.githubusercontent.com/39909394/49290314-c9eb3080-f48d-11e8-8c7d-4519b420148e.png)

**Comment by uprel** [comment]
Looks like problem on screen is just because PHP Strict standard variable is different. I will have to check setup on Windows, but you must have some errors also in Apache error.log. Check there
