### ISSUE TITLE
problem with geosearch after searching and moving in the map a little

### ISSUE THREAD

**Issue by smemorex** [uprel/gisapp#31]
hello,
i can see this problem also in your demo

http://test.level2.si/gisapp/eu_demo?public=on&lang=en

in desktop version , do a search clicking to see result , list of possible result where go away, in the bar you see only what you selecet , when zoomed click on bar and erase street name with keyboard , now search doesn't work , you have to click reset button , i don't understand why it happened only when you move the map

**Comment by uprel** [comment]
Confirmed, will take a look.

**Comment by uprel** [comment]
Change in Geocode configuration also fixed that issue. Commit 4d4ddc172673524b45cbecd4537df445b70fb3d3
