### ISSUE TITLE
StreetView panel size

### ISSUE THREAD

**Issue by uprel** [uprel/gisapp#4]
Not fully resized within panel on first click

**Comment by scramatte** [comment]
When you resize the panel the Google street view is not refreshed.
When you increase size I got  black space on the left.  If  I resize de window  view is refreshed properly.

**Comment by uprel** [comment]
I will take a look.

**Comment by scramatte** [comment]
Hi, 

It's still doesn't works. When you change size of the panel the streeview  is not refreshed. Browser resize it's ok.

**Comment by scramatte** [comment]
Hi,

Any chance to fix this annoying bug ?

![image](https://user-images.githubusercontent.com/188766/95492989-224dbc00-099c-11eb-9ebc-7c6a6a1b6766.png)


Regards

**Comment by uprel** [comment]
Done, also with auto map panning
