### ISSUE TITLE
Configuring Search Panel for map

### ISSUE THREAD

**Issue by Prajith76** [uprel/gisapp#52]
I would appreciate if anybody can help to show how to configure the search panel in Extended QGIS Web client for a particular layer.

**Comment by uprel** [comment]
Hi, you probably saw example on Wiki. And if you really can't go through with it you can send me details by email.

**Comment by uprel** [comment]
Closing, as problem was explained.

**Comment by Prajith76** [comment]
Thanks a lot for your help and support, much appreciated
