### ISSUE TITLE
Add Title, Description and User to PDF Print

### ISSUE THREAD

**Issue by uprel** [uprel/gisapp#53]
Extend print window with optional user title and description.
Add username of current EQWC user.
Solution will work on writing data to temp postgres table where Print Layout will read data from.

**Comment by miszokienka** [comment]
Is it already working well?
I've added table users_print_view and there is correct data inside but when I try to get a pdf in EQWC fields from table are NULL value. Seems like the table is not recognized by EQWC at all or table must be visible in layers TOC in EQWC to put values into Print composer.

**Comment by uprel** [comment]
Yes, but it's not documented yet. 

1. Add users_print_view to QGIS legend tree. It is hidden from Web client.
2. Add table to Print Composer. You will always have only 1 result, you can add it more times and customize it, to have title on top with different text, then for example user and description somewhere else.

**Comment by uprel** [comment]
Now also documentation on [Wiki](https://github.com/uprel/gisapp/wiki/5.5.-Print#setup)
