### ISSUE TITLE
Mobile client -  Mobile view is not detected on nexus 7 tablet

### ISSUE THREAD

**Issue by scramatte** [uprel/gisapp#54]
Mobile view is not detected on nexus 7 tablet.

**Comment by uprel** [comment]
Setting is now that phones get mobile client, but tablets don't. Mobile detection is done on server side, so I don't get screen sizes. I could add some specific conditions. Can you open this test site with Nexus 7 and get back which true values are reported. http://demo.mobiledetect.net/

**Comment by uprel** [comment]
Another option is that you add mobile=on parameter to URL.

**Comment by uprel** [comment]
Well, one simple solution, if this is still relevant, is to just force all tablets to open as mobile client. Change this line
https://github.com/uprel/gisapp/blob/179122f82db5a332b3baf3e62e92e2724b8cc554/index.php#L198

to

`if( $detect->isMobile()){ `
