### ISSUE TITLE
Custom Projections

### ISSUE THREAD

**Issue by ale12a** [uprel/gisapp#55]
Hi,
in customProjections.js you wrote:
"You can get it from https://epsg.io (copy projected bounds) or from baselayer definition."
I want to add projection for italy EPSG:32633, from https://epsg.io I found this values
Projected bounds:
166021.44 0.00
534994.66 9329005.18
Do I have to do some transformation to get the values to include in the file?

For EPSG:32635 in customProjections.js you have
{extent: [-760000, 6580000, 657000, 8990000], units: 'm', yx: false};
but in https://epsg.io there is 
Projected bounds:
166021.44 0.00
534994.66 9329005.18

Thanks in advance

**Comment by uprel** [comment]
This extent is only relevant when you run client without any base layer. In case of base layer, extent is set from there. You can insert projected bounds, for 32635 this are really custom values that were overriden by base layer extent, so it should be projected bounds from epsg.io
