### ISSUE TITLE
Add tiles layer as baselayer

### ISSUE THREAD

**Issue by UserGis** [uprel/gisapp#56]
Hi. I have a many aerial photos. I create tiles with QTiles Qgis plugin. How can I display custom layer with tiles as a baselayer?

**Comment by uprel** [comment]
With Qtiles I didn't try yet. Actually I wanted to, but it just crashes my QGIS every time. It suppose to generate mbtiles and directory structure which could be supported in Open Layers.
Now supported formats are standard WMS or tile formats WMTS, XYZ, for TMS I have to check. It's basically same as XYZ. Normally you get this from special Map Tile server. If Qtiles generates data in one of this two formats than it would be possible.

**Comment by msznabel** [comment]
For many aerial photos I use geoserver and serve to EQWC as WMTS. It's work great.

**Comment by uprel** [comment]
OK, Good to know that you manage it. I also recommend this option, I should write short tutorial about this (when it's time).
Also you will be interested that there is now some progress with printing tile layers. Idea is to put base layer to QGIS project (WMS,WMTS, OpenstreetMap) and then also add it to database project as baselayer. If layers are same name, layer from QGIS will not appear in legend but it will be used when printing. This works for WMS and OpenstreetMap, but for WMTS is related to specific GDAL version. I will have to test this more and write docs about it. You can try demo project on test.level2.si

**Comment by miszokienka** [comment]
Will it be possible to add also TMS as a printable base layer the same way as WMS and OpenstreetMap?

**Comment by uprel** [comment]
I think it is related to GDAL. So with newer build it should be possible to add WMTS and we have to test also about TMS. Here is [documentation on this part](https://github.com/uprel/gisapp/wiki/5.5.-Print#base-layers).

**Comment by uprel** [comment]
I will close this issue, since main question is answered and off topic. For printing various base layers it would be best to open new issue.
