### ISSUE TITLE
Projection is not working when add a EPSG32648.js file

### ISSUE THREAD

**Issue by whiteshonkhor** [uprel/gisapp#57]
Hello, 

Gisapp is not projecting my project when i choose EPSG:32648 even it is working fine when EPSG files are coressponding in /gisapp/client/site/libs/proj4js/defs/.

The app is not working however i changed configurations as guideline. 
I created EPSG32648.js file in /gisapp/client/site/libs/proj4js/defs/ and CRS was added to  gisapp/client_common/customProjections.js.

Is there any other configurations ? Could you help me ?

**Comment by uprel** [comment]
Assuming you done all this but anyway:
1. Projection is determined upon baselayer, so if you have baselayer in any other projection than that is the reason.
2. Your QGIS project must be saved in that projection.
3. Log out, go back in and do CTRL+F5 to hard refresh site.

What is the problem? Is the map totally streched in wrong proportions?

**Comment by whiteshonkhor** [comment]
The problem is shapes not showing to EPSG32648 even its data came to attribute and shapes were shown in EPSG3857. 

Can i use "+proj=utm +zone=48 +datum=WGS84 +units=m +no_defs" for my EPSG32648.js or should i convert my project to EPSG3857 ?

**Comment by whiteshonkhor** [comment]
Dear Uros Preloznik,

The problem is shapes not shown to EPSG32648 even its data came to
attribute and shapes were shown in EPSG3857.

Can i use "+proj=utm +zone=48 +datum=WGS84 +units=m +no_defs" for my
EPSG32648.js or should i convert my project to EPSG3857 ?



Regards,

Whiteshonkhor

**Comment by uprel** [comment]
It should be possible. You could contact me by email and I can help

**Comment by uprel** [comment]
There was indeed problem in case you have project in custom projection, no base layers and no reprojection on the fly was used (OTF was off). CRS code was wrong taken from QGIS project and you get blank screen with error in console.
I tested this and commited fix, can you try and get back with results.

**Comment by uprel** [comment]
I will close this, since I do not get feedback of any problems after the update
