### ISSUE TITLE
tiling qgis queries

### ISSUE THREAD

**Issue by msznabel** [uprel/gisapp#58]
Have you thought about putt tails into queries to qgis? This would speed up read data (prepare data for several qgis_mapserv.fcgi at the same time).
regards

**Comment by uprel** [comment]
Default option is really to use single sized image. Here:
https://github.com/uprel/gisapp/blob/fc34d219f4b1184fe86e544e2ff2980c13b31ffd/client/site/js/LoadAppProjectData.js#L289

Did you try it? Does it work for you better?

Using tiles is problematic when you display labels in QGIS project, that labels can be cut with tiles. So I think if this is needed it should be up to the user to set this up per specific project, so I could prepare setting in database.

**Comment by miszokienka** [comment]
I will be also interested to test tiles.

**Comment by uprel** [comment]
You can try it now by changing singleTile to false in above file.

Also note that you have to set debug variable to TRUE in admin/settings.php. This way client will use this source js files instead of single compact eqwc.js which I publish with every release.

**Comment by msznabel** [comment]
It's doesn't work. When I change it to false then I don't see any map :(

**Comment by uprel** [comment]
Can you debug this little in browser: Hit F12 to get developers console and look for any errors. Also check URL of tiles send to QGIS project in Network tab. What was the response from those calls (empty picture or error)

**Comment by msznabel** [comment]
ok, it's work, but it's horrible slow. I don't wait enought before:( 
It's work much slower then with single tile also with helloworld projekt.

**Comment by uprel** [comment]
True. Requests to tiles are coming in synchrone mode, meaning one by one. So I think that's the reason for slow performance, every request now waits for previous to finish.
