### ISSUE TITLE
Search mobile client

### ISSUE THREAD

**Issue by UserGis** [uprel/gisapp#59]
Hi, how can I set the search for mobile client to search certain layer from projects?
Thanks

**Comment by uprel** [comment]
Currently this option is not implemented. Mobile viewer uses different code. If you need this feature you can contact me by email and we will discuss details.

**Comment by uprel** [comment]
With first comment I was referring to Search Panels. Now it's possible to setup local search to Postgis data using WSGI - search combo. This also works in mobile client.
Read more - [ here (part 2.2)](https://github.com/uprel/gisapp/wiki/5.2.-JSON#2-search-combo)
