### ISSUE TITLE
Select Feature by click

### ISSUE THREAD

**Issue by ale12a** [uprel/gisapp#60]
Hi,
there is a method to select feature by clicking on it on the map?
In this moment to select a features I have to open attribute table and than click icon in ActionColum in feature row.

Thanks

**Comment by uprel** [comment]
Yes it is, I have to update Wiki on this part:

1. In project properties -> OWS Server set "Use layer ids as names"
1. Same settings under WFS publish layers you want to use selection
1. In Web Client click on feature for identify and you will see arrow icon to select feature geometry.

**Comment by uprel** [comment]
[Documentation here](https://github.com/uprel/gisapp/wiki/5.-Project-configuration#1-project-properties)
Closing
