### ISSUE TITLE
legend on mobile

### ISSUE THREAD

**Issue by DamienFRAZZONI** [uprel/gisapp#62]
There is no legend on mobile version, only the name of the layers.
That would be a great think to publish QGIS project with symbology on web responsive design format

**Comment by uprel** [comment]
I agree, but mobile client uses dfferent code so it is some extra work to do that.

**Comment by uprel** [comment]
Reopened again, because it needs some refactoring. Basically it will not show/hide regarding layer visibility but will have another icon to show/hide label
