### ISSUE TITLE
No add Title, Description fields in print map

### ISSUE THREAD

**Issue by gesme** [uprel/gisapp#67]
Hello,

I have no fields in the printmap settings to add a tittle or description.
<img width="470" alt="ecwc_no_fields" src="https://user-images.githubusercontent.com/6114095/34821422-f13159d0-f6c3-11e7-9fee-38cbaaf48024.png">
Can you help me ? everything else works fine.

Thanks,

**Comment by uprel** [comment]
Reason for this is that you are logged in as guest (public access). In this case those fields are hidden. Try registering new user and add permission to the project for that user and login as user.
https://github.com/uprel/gisapp/wiki/3.-Managing-Database#users
