### ISSUE TITLE
Using relations in QGIS does not work in Web Client

### ISSUE THREAD

**Issue by news24lor** [uprel/gisapp#71]
I have a layer of polygons with data connected via the Joins function and a large table connected through the Relations function. Everything works very well on QGIS.
When I go to gisapp by pressing on the polygon I see only the data of the layer and not that connected via Joins and not even those linked through Relations. One of the most useful things is to see the connected data.
Is it a gisapp limit or is it a bug?
Thanks

**Comment by uprel** [comment]
I tested joining two shape files in QGIS 2.18 and I got join fields in identify window and attribute table, so joining works.
Relations are more complex and it is more matter of QGIS Desktop and if you don't get response from related table in gisapp means that QGIS Server via WMS GetFeatureInfo request does not support that. I did not tested, though.

**Comment by news24lor** [comment]
Hi @uprel 
I've used QGIS 2.14 and joins feature does not work.
Now I've installed new QGIS 2.18 and I see the data linked with joins feature. Very Good!
Relations method does not work. Do you think that there is a limit in WMS GetFeatureInfo?
Thanks for your answer

**Comment by uprel** [comment]
Relations are supported with upcoming release 1.9.0. All necessary code is already commited into master, I will prepare documentation on this. Relations are configured with project json file and don't need to be prepare in QGIS project, just tables must exist there.
QGIS Server 2.18 is not supported anymore.
