### ISSUE TITLE
A strange problem

### ISSUE THREAD

**Issue by news24lor** [uprel/gisapp#74]
I can't use gisapp. For some strange reason the settings.php is not loaded and the PROJECT_PATH where the demo is located is not seen and I do not understand the cause. Gisportal works and PostgreSQL also works well.
I confirm that QGIS Server works well with other software and everything else works well. I have PHP 7.2.1 installed and I have Apache with multiple sites in virtual hosts.
I have done all the settings according to the instructions but when I go to see "/gisapp/helloworld" I always have the same error:
The requested URL /gisapp/helloworld was not found on this server'.

Do I need special modules in PHP and Apache?
It's a puzzle....

A help, thanks

**Comment by news24lor** [comment]
In apache I had naturally inserted gisapp.conf while I didn't 'serve-cgi-bin.conf'.
Is this the problem?

**Comment by uprel** [comment]
Yes might, serve-cgi-bin should also be running. Please look at requirements page and setup page again, if you missed a step or two.

**Comment by news24lor** [comment]
I tried in two computer:
- one  is normal with only one website e localhost is the same of the website. In this case gisapp works very well;
in httpd.conf
Alias /gisapp/ /myhd/server/www/gisapp/

- the other one has many virtual host and in this case gisapp does not work.
in httpd.conf
Alias /gisapp/ /myhd/server/www/site1.com/gisapp/

It's a problem of configuration inside httpd.conf but I don't know where

**Comment by news24lor** [comment]
Hi @uprel 

The problem is resolved.

I have many virtual hosts and the gisapp.conf goes inside the virtual host con.

Example:

 ```
<VirtualHost *:80>
     ServerAdmin myemail@xxx.com
     DocumentRoot "/myhd/server/www/site1.com/"
     ServerName site1.com
     ServerAlias site1.com
     
	Alias /gisapp/ /myhd/server/www/site1.com/gisapp/
	#displaying SVG icons (mobile client)
	AddType image/svg+xml svg
	#Fixing IE error CSS was ignored due to mime type mismatch
	AddType text/css css

	RewriteEngine On
	RewriteRule ^/proxy/(.+)$ /gisapp/admin/qgisproxy.php?map=$1.qgs [QSA,PT]

	RewriteRule ^/gisapp/([^\.]+)$ /gisapp/index.php [PT]
 
	<IfModule mod_fcgid.c>
        # GISAPP and GISPORTAL
		FcgidInitialEnv LC_ALL "en_US.UTF-8"
		FcgidInitialEnv PYTHONIOENCODING UTF-8
		FcgidInitialEnv LANG "en_US.UTF-8"
	</IfModule>
     
 </VirtualHost>

```

Please, insert a note about the configuration for multisite

Thanks

**Comment by uprel** [comment]
That's ok that you managed it. I know this setups are not just out of the box so everyone setting this up should know little about setting up Apache.
You could still use gisapp configuration inside VirtualHost with
`Include gisapp.conf`
