### ISSUE TITLE
Add option (button, link) to switch between mobile and regular client

### ISSUE THREAD

**Issue by uprel** [uprel/gisapp#76]
Now only option is to force opening mobile client with mobile=on parameter. If you want to open desktop client from mobile is not possible.

**Comment by miszokienka** [comment]
Uros, it's possible by setting Desktop mode in your mobile web browser. But i.e. _mobile=off_ or _desktop=on_ will be the better solution.

**Comment by uprel** [comment]
When mobile client is opened by default on phone, you cannot go to desktop client, so that's main problem. And also if you setup that also tablets are using mobile client by default then you cannot use desktop client on tablet.

**Comment by uprel** [comment]
> Uros, it's possible by setting Desktop mode in your mobile web browser. But i.e. _mobile=off_ or _desktop=on_ will be the better solution.

Yes, this Desktop link works quite well, so I don't see the need to implement anything else. By default tablets use desktop mode, which for most users should be just open mobile version and then use this desktop link if needed.
