### ISSUE TITLE
Data from **users_print_view** is not printing

### ISSUE THREAD

**Issue by miszokienka** [uprel/gisapp#78]
If you have added _users_print_view_ table to qgis project and then use it's values in printing it's not taking values from the table. It's a fresh bug.
I think it's connected with recent changes in gisapp because there is no problem if you rename _users_print_view_ in qgis project to any other name. Of course if you rename it it's shown in the layer's tree.

**Comment by uprel** [comment]
Ok it's possible that there is problem regarding latest changes. I will check

**Comment by uprel** [comment]
Fixed in release 1.7.4
