### ISSUE TITLE
Export layers

### ISSUE THREAD

**Issue by Csantos11** [uprel/gisapp#8]
Hello,
I trying to setup a webgis using QGIS server and Extended QGIS Web Client, and with a lot of help, i'm able to see my data thought browser. 
I personally like the features of EQWC, but unfortunately due to data polices i can not share the information in a shp format, so what a want to know is if it is possible to disable the export features for all layers, or a specific number of layers.
Regards

**Comment by uprel** [comment]
Makes sense, will look at it shortly.

**Comment by uprel** [comment]
How about if we just simply disable this feature for Guest access in general? Registered users (which you control) will have this option as it is now. That way it's not needed to adjust this per layer or project.

**Comment by Csantos11** [comment]
That's a good idea
But the are still some data i want to display as jpeg or png, that i can not redistribute as shp even to a controlled group.

**Comment by uprel** [comment]
First part is done with release 1.0.0, today. For second part I will prepare update to control export only per layers that have WFS publish option enabled in QGIS Project Settings. Since there is no specific plugin for QGIS to control this, it makes sense to rely on WFS publish option.

**Comment by uprel** [comment]
Well, oldest issue gone. Probably not relevant for you, but it is for other people. Together with latest gisportal update, there is now new role available that prevents using export functionality. Done in gisapp with 1.9.14
