### ISSUE TITLE
Hide the column in the "Results" window

### ISSUE THREAD

**Issue by UnoRed1** [uprel/gisapp#81]
Hello. How to hide the column in the "Results" window?

**Comment by miszokienka** [comment]
If you mean hiding from GetFeatureInfo requests (no info for a field from attribute table after a click on a feature) then you have to go in QGIS to layer properties, then fields tab and uncheck WMS for the fields you don't want to publish.

**Comment by UnoRed1** [comment]
Thank you so much!
