### ISSUE TITLE
Print only features filtered within attribute table

### ISSUE THREAD

**Issue by miszokienka** [uprel/gisapp#83]
If you filter attribute table than you get a view of only filtered features on the map. The idea is to also print only filtered features. For now, even if features on the map get filtered, prints have all the features of the layer.

**Comment by uprel** [comment]
When fixing this also:

- [ ] Clear filter on one table, clears all map filters (should only for coresponding layer)
- [ ] When printing filter is already used for users print table (title, description), so that needs to remain and combine new filter from map with this

**Comment by uprel** [comment]
Map filter is done also on Print with this commit 2a06fd4ca3d1ecb6829b346e9b91f1e55fc6f6ce
