### ISSUE TITLE
Redirect to start page issue

### ISSUE THREAD

**Issue by scramatte** [uprel/gisapp#85]
Hello,

I'm trying to publish a new project to gisapp and I got the following error.
helloworld.qgs works fine

Any idea of what occurs ?

<img width="272" alt="imagen" src="https://user-images.githubusercontent.com/188766/43909552-e4799c34-9bfa-11e8-872f-f3a1a4970dc1.png">

**Comment by scramatte** [comment]
It looks that the issue is related to base_layers. When I disable whole base_layers , it works properly.
Might be a problem with our CRS.  We use EPSG:25830

**Comment by miszokienka** [comment]
Try with setting your QGIS project to EPSG:3857.
It's described [here](https://github.com/uprel/gisapp/wiki/5.4.-CRS).

**Comment by scramatte** [comment]
Yes it works If  I change the QGIS project CRS. Does it posible to load Google layers or OSM  using ESPG:25830 ?

**Comment by uprel** [comment]
No it will not work. Google, OSM, Bing, Mapbox and similar use only 3857 projection, at least as far as I know.  You can have your data in any other projection but must then use reprojection of QGIS project on the fly, which might slow down QGIS server.
About the issue, I was lately working on to improve warning and feedback to users in case of map loading error, but in some cases like timeout works little weird if you get redirected.

**Comment by uprel** [comment]
This commit 87aed73e3be29acb80cf194b0b14c7ddd346da31, removes redirect to start page in case of issue with QGIS server call. You stil get error message.
Closing, since we know real issue.
