### ISSUE TITLE
v1.8.0 - gisapp does't load 

### ISSUE THREAD

**Issue by miszokienka** [uprel/gisapp#92]
I tried to update my gisapp version and after an update gisapp was't loading. After that I've set up a new virtual machine with Linux Mint (18.3 and 19) and tried various versions of QGIS Server with various gisapp versions. New installation made with following wiki step-by-step is working only until v1.7.5. After updating to v1.8.0 or while setting up a gisapp instance directly as v1.8.0 it's loading just nothing in web browser after opening http://localhost/gisapp/helloworld. 
So... something must have changed between v1.7.5 and v1.8.0 that causes this bug. Is it all working well at your side Uros?

**Comment by uprel** [comment]
Weird, must be some errors in console. Can you check and paste it?

**Comment by uprel** [comment]
Also please check apache error.log, because 1.8.0 adds new variables in settings.php. It should work without them, but still maybe I missed something there.

**Comment by uprel** [comment]
Problem was rPolish translation file. Fixed with 5ef5bf99cbbc5f0120fae1ef84a29d9770b110aa
