### ISSUE TITLE
In Map Layers, legend icons/images not showing up when opening project with  IE11 and Windows7

### ISSUE THREAD

**Issue by hiroki-c** [uprel/gisapp#96]
Hi

I successfully set up qgis server3.4 and eqwc 1.8.2 on Ubuntu 18.04.

When I checked the sample hello project with IE11&Windows7 with EQWC,
I noticed that legend images not showing in map layer. * Please check the attachment below.

Firefox 64 and Google Chrome 71 work correctly but when I open my project with IE11,
it gives me an error in console like below

"Unable to get property 'getUI' of undefined or null reference"
at file: eqwc.js, row: 43, column:437

below script is the part that may be giving an error
`Ext.DomHelper.insertAfter(b.getUI().getAnchor(),"<div style='overflow-x:hidden; overflow-y:auto; max-height:"+ h+"px;' id='legend_"+c+"'><img style='vertical-align: middle; margin-left: 50px;margin-bottom: 10px;' src=\""+a+'"/></div>');`

Any ideas on this issue?
We need to use IE11 because most people in our company are only available to use IE11.

![error](https://user-images.githubusercontent.com/46952432/51586605-39771c80-1f21-11e9-8da4-2f1e3ced58e8.PNG)

**Comment by uprel** [comment]
I checked, code used here is not implemented in IE11 so a workaround is needed.
Source - https://stackoverflow.com/questions/8056277/how-to-get-response-url-in-xmlhttprequest

Server must provide custom header with data needed (node id and layer) and then it can br requested with xhr.getResponseHeader()

All other major browsers support that, so problem is really IE. If you can't use any other and you really wish to display legend like that, I can provide this fix.

**Comment by hiroki-c** [comment]
Thank you for the quick response Uprel.

It would be great if you could provide us the modification for this 
if that doesn’t take too much time for you!

Since we have a lot of categories to display, showing legend images is really helpful for us:)

Thank you

Thank you

**Comment by hcwk** [comment]
Hi

Any update for this issue?

Thank you

**Comment by uprel** [comment]
A lot of other work, sorry. I could take a look this week and since you are more or less only one requesting this I would appreciate that if after the update you consider some donation to the project.

**Comment by hcwk** [comment]
Thank you Uprel, I will consider about it for sure!

**Comment by uprel** [comment]
Done with release 1.8.3

https://github.com/uprel/gisapp/releases/tag/v1.8.3

 

Check it out and let me know if any problems

**Comment by hiroki-c** [comment]
Thank you Uprel for your work!
I will check it today

**Comment by uprel** [comment]
I updated also code on test.level2.si so examples using IE11 should show legends

**Comment by hiroki-c** [comment]
Hi Uprel, it's working perfectly. Now I can see legends on IE11.
Thank you very much.
