### ISSUE TITLE
Skip non identify layer from QUERY_LAYERS array for GetFeatureInfo

### ISSUE THREAD

**Issue by uprel** [uprel/gisapp#99]
Mobile client currently does not check if layer has checked identify in QGIS project properties.
QGIS Server 3.4.5 throws "Layer not queriable" in such case without any other results.

**Comment by scramatte** [comment]
![image](https://user-images.githubusercontent.com/188766/65343770-20209000-dbd6-11e9-8d56-70ec015fe150.png)

It looks that my layers are ok ...
